pricealerts/views/alerts.py
import requests
from bs4 import BeautifulSoup, SoupStrainer
from flask import Blueprint, url_for, request, flash, render_template
from flask_login import login_required, current_user
from werkzeug.utils import redirect

from pricealerts import StoreModel, ItemModel, AlertModel, UserModel
from pricealerts.forms import AlertForm
from pricealerts.models import StoreNotFoundError, ItemNotLoadedError
from pricealerts.settings import env
from pricealerts.utils.notifications import NotificationDispatcher

alert_blueprint = Blueprint('alerts', __name__, url_prefix='/alerts', template_folder='templates')


@alert_blueprint.route('/create', methods=['GET', 'POST'])
@login_required
def create_alert():
    form = AlertForm()


    if request.method == 'GET':
        return render_template('store/new_alert.html', form=form)

    validate = form.validate_on_submit()  # This is a shortcut for form.is_submitted() and form.validate().
    if validate:

        # Request method is POST
        prod_url = form.url.data
        # store_id = int(request.form['store_id'])
        price_limit = float(form.data['price_limit'])
        check_frequency = int(form.data['check_frequency'])
        alert_email = form.data['alert_email']
        alert_phone = form.data['alert_phone']

        active = bool(form.data['active'])

        user = UserModel.find_one(username=current_user.username)

        try:
            store = StoreModel.find_by_url(prod_url)
        except StoreNotFoundError:
            only_title = SoupStrainer('title')
            # Find the store on Internet
            from urllib.parse import urlparse
            o = urlparse(prod_url)

            if o.netloc is None:
                location = o.path.split('/')[0]
            else:
                location = o.netloc

            store_url = o.scheme + "://" + location
            req = requests.get(store_url)
            html_doc = req.content
            soup = BeautifulSoup(html_doc, 'html.parser', parse_only=only_title)

            store = StoreModel(soup.title.string, store_url).save_to_db()

        # Create the item
        item = ItemModel(prod_url, store_id=store.id)

        try:
            item.name, item.price, item.image = item.load_item_data()
        except ItemNotLoadedError as ex:
            flash(ex.message, category='error')
            return redirect(url_for('users.user_alerts'))


        item.save_to_db()

        # Create the alert
        alert = AlertModel(price_limit, item.id, user.id, check_every=check_frequency,
                   contact_email=alert_email, contact_phone=alert_phone,
                   active=active).save_to_db()

        subject = "NEW ALERT CREATED from Pricing Alert Service <{}>".format(env('SMTP_USER')),
        message = "New Price Alert has been created for {}.<br>{} <{}> have setup this email address ({})" \
                  "to receive alerts regarding prices drops over this product. <br/>You can now seat down" \
                  "and let us do the hard work".format(item.name, user.name, user.username, alert_email)

        if not NotificationDispatcher.send_email(user.name, user.username, alert.contact_email,
                                          subject=subject, message=message):
            flash('Error sending email to {}. A notification has been '
                  'emitted to the system administrator'.format(alert.contact_email), category='error')


        if alert.contact_phone is not None and alert.contact_phone != "":
            if not NotificationDispatcher.send_sms(
                    from_name="Pricing Alert Service",
                    to_phone=alert.contact_phone,
                    to_name=user.name,
                    text='New Alert for {} and price limit {} was added.'.format(alert.item.name, alert.price_limit)):

                flash('Error sending SMS to {}. A notification has been '
                      'emitted to the system administrator'.format(alert.contact_phone), category='error')

        # After saving all data redirect to user alerts page
        return redirect(url_for('users.user_alerts'))


    return render_template('store/new_alert.html', form=form)


@alert_blueprint.route('/edit/<int:alert_id>', methods=['GET', 'POST'])
@login_required
def edit_alert(alert_id):
    alert = AlertModel.find_by_id(alert_id)

    if not alert:
        flash("Alert not found", category='error')
        return redirect(url_for('users.user_alerts'))

    curr_url = alert.item.url
    form = AlertForm(request.form)

    if request.method == 'POST' and form.validate():
        form.populate_obj(alert)
        alert.item.url=curr_url
        alert.save_to_db()

        user = UserModel.find_one(username=current_user.username)

        subject = "ALERT MODIFIED from Pricing Alert Service <{}>".format(env('EMAIL_FROM')),
        message = "New Price Alert has been updated for {}.<br>"
        "{} <{}> have setup this email address ({}) to receive alerts regarding prices"
        "drops over this product. <br/>"
        "You can now seat down and let us do "
        "the hard work".format(alert.item.name, user.name, user.username, alert.contact_email)

        if not NotificationDispatcher.send_email(user.name, user.username, alert.contact_email,
                                          subject=subject, message=message):
            flash('Error sending email to {}. A notification has been '
                  'emitted to the system administrator'.format(alert.contact_emaiil), category='error')

        if alert.contact_phone is not None and alert.contact_phone != "":
            if not NotificationDispatcher.send_sms(
                    from_name="Pricing Alert Service",
                    to_phone=alert.contact_phone,
                    to_name=user.name,
                    text='New Alert for {} and price limit {} was added.'.format(alert.item.name, alert.price_limit)):

                flash('Error sending SMS to {}. A notification has been '
                      'emitted to the system administrator'.format(alert.contact_phone), category='error')

        return redirect(url_for('users.user_alerts'))

    return render_template('store/edit_alert.html',
                           username=current_user.username if current_user.username is not None else 'Buyer',
                           alert=alert)



@alert_blueprint.route('/activate_deactivate/<int:alert_id>')
@login_required
def activate_deactivate_alert(alert_id):
    alert = AlertModel.find_by_id(alert_id)
    if alert:
        alert.active = not alert.active
        alert.save_to_db()
    return redirect(url_for('users.user_alerts'))

pricealerts/views/globals_views.py
from flask import (
    Blueprint, render_template, jsonify)
from flask_login import current_user, login_required

global_bp = Blueprint('site', __name__)


@global_bp.route('/')
@global_bp.route('/home')
def home():
    return render_template('store/home.html',
                           current_user=current_user)


@global_bp.route('/contact', methods=['GET', 'POST'])
@login_required
def contact():
    return render_template('store/contact.html')


@global_bp.route('/about')
def about():
    return render_template('store/about.html')


@global_bp.route('/json')
def json():
    return jsonify({'message': "Hello, World!"})

# a simple page that says hello
@global_bp.route('/hello')
def hello():
    return 'Hello, World!'

pricealerts/templates/store/_brandname.html
Prices Alerts

pricealerts/templates/store/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

pricealerts/templates/store/alerts.html
{% extends "store/base.html" %}

{% block page_name %} Listing your alerts {% endblock %}

{% block styles %}
{{super()}}
<style>
    .view-group {
    display: -ms-flexbox;
    display: flex;
    -ms-flex-direction: row;
    flex-direction: row;
    padding-left: 0;
    margin-bottom: 0;
}
.thumbnail
{
    margin-bottom: 30px;
    padding: 0px;
    -webkit-border-radius: 0px;
    -moz-border-radius: 0px;
    border-radius: 0px;
}

.item.list-group-item
{
    float: none;
    width: 100%;
    background-color: #fff;
    margin-bottom: 30px;
    -ms-flex: 0 0 100%;
    flex: 0 0 100%;
    max-width: 100%;
    padding: 0 1rem;
    border: 0;
}
.item.list-group-item .img-event {
    float: left;
    width: 30%;
}

.item.list-group-item .list-group-image
{
    margin-right: 10px;
}
.item.list-group-item .thumbnail
{
    margin-bottom: 0px;
    display: inline-block;
}
.item.list-group-item .caption
{
    float: left;
    width: 70%;
    margin: 0;
}

.item.list-group-item:before, .item.list-group-item:after
{
    display: table;
    content: " ";
}

.item.list-group-item:after
{
    clear: both;
}

</style>
{% endblock %}


{% block main %}
<!--<header>-->
<!--<div class="collapse bg-dark" id="navbarHeader">-->
<!--<div class="container">-->
<!--<div class="row">-->
<!--<div class="col-sm-8 col-md-7 py-4">-->
<!--<h4 class="text-white">About</h4>-->
<!--<p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>-->
<!--</div>-->
<!--<div class="col-sm-4 offset-md-1 py-4">-->
<!--<h4 class="text-white">Contact</h4>-->
<!--<ul class="list-unstyled">-->
<!--<li><a href="#" class="text-white">Follow on Twitter</a></li>-->
<!--<li><a href="#" class="text-white">Like on Facebook</a></li>-->
<!--<li><a href="#" class="text-white">Email me</a></li>-->
<!--</ul>-->
<!--</div>-->
<!--</div>-->
<!--</div>-->
<!--</div>-->
<!--<div class="navbar navbar-dark bg-dark shadow-sm">-->
<!--<div class="container d-flex justify-content-between">-->
<!--<a href="#" class="navbar-brand d-flex align-items-center">-->
<!--<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>-->
<!--<strong>Album</strong>-->
<!--</a>-->
<!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">-->
<!--<span class="navbar-toggler-icon"></span>-->
<!--</button>-->
<!--</div>-->
<!--</div>-->
<!--</header>-->

<main role="main">
    <div class="container">
        {% if alerts | length == 0 %}
        <p class="lead">There is not saved alerts for {{ current_user.name }}. </p>
        <p>
                <a class="btn btn-primary btn-lg my-2" href="{{ url_for ('alerts.create_alert') }}">I want to create a
                    product price alert</a>
                <!--<a href="#" class="btn btn-secondary my-2">Review my alerts</a>-->
            </p>
        {% else %}
        <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2" role="group" aria-label="First group">

                <a class="btn btn-primary my-2" href="{{ url_for ('alerts.create_alert') }}">New price alert</a>


            </div>

            <div class="btn-group mr-2" role="group" aria-label="Second group">
                <button class="btn btn-info btn-secondary"  type="button" id="list">
                    List View
                </button>
                <button class="btn btn-danger btn-secondary" type="button" id="grid">
                    Grid View
                </button>
              </div>

        </div>

        <div id="products" class="row view-group">
            {% for alert in alerts %}
            <div class="item col-xs-4 col-lg-4">
                <div class="thumbnail card">
                    <div class="img-event">
                        <img class="group list-group-image img-fluid" src="{% if alert.item.image %} {{ alert.item.image }} {% else %} http://placehold.it/400x250/000/fff {% endif %}" alt=""/>
                    </div>
                    <div class="caption card-body">
                        <h4 class="group card-title inner list-group-item-heading">
                            {{ alert.title}} </h4>
                        <p class="group inner list-group-item-text">
                            At {{ alert.item.store.url_prefix }} <br>
                            Price limit: $ {{ alert.price_limit }} / Current Price: $ {{ alert.item.price }}<br>
                            <small>Last checked: {{ alert.last_checked_delay }} mins ago</small>
                        </p>
                        <div class="row">
                            <div class="col-xs-12 col-md-4">
                                <p class="lead">
                                    $ {{ alert.item.price }}</p>
                            </div>

                            <div class="col-xs-12 col-md-4 d-flex justify-content-between align-items-right">
                                <div class="btn-group">
                                    <a href="{{ url_for ('alerts.activate_deactivate_alert', alert_id=alert.id) }}">
                                        <button type="button" class="btn btn-sm btn-success">{% if
                                            alert.active == true %}Deactivate {% else %}Activate {% endif %}
                                        </button>
                                    </a> &nbsp;
                                    <a href="{{ url_for ('alerts.edit_alert', alert_id=alert.id) }}">
                                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                    </a>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}

        </div>

        {% endif %}
    </div>

</main>


{% endblock %}

{% block scripts %}
{{super()}}
<script>
    $('#list').click(function(event){event.preventDefault();$('#products .item').addClass('list-group-item');});
            $('#grid').click(function(event){event.preventDefault();$('#products .item').removeClass('list-group-item');$('#products .item').addClass('grid-group-item');});

</script>
{% endblock %}

pricealerts/templates/store/base.html
{% extends "bootstrap/base.html" %}
{# {% import "bootstrap/fixes.html" as fixes %} #}
{% import "bootstrap/utils.html" as utils %}
{% block head %}
{{super()}}
{# {{fixes.ie8()}} #}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" class="holderjs">
{% endblock %}


{% block title %}
{% include "store/_brandname.html" %} - {% block page_name %} Get Prices Alerts! {% endblock %}
{% endblock %}

{% block styles %}
<!-- Bootstrap CSS -->
{% if current_user.is_anonymous %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
{% endif %}
{% if current_user.theme %}
<link rel="stylesheet" href="{{ current_user.theme }}">
{% else %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
{% endif %}

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<!--Style for this site-->
<link rel="stylesheet" href="{{ url_for('static', filename='css/store.css')}}">

{% endblock styles %}

{% block navbar %}
<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark fixed-top ">
    <a class="navbar-brand" href="{{ url_for ('site.home') }}">
        {% block navbar_brand %}
        <!--src="{{ url_for( 'static', filename='site/img/logo.png') }}"-->
        <img data-src="holder.js/64x64?theme=sky&font=Material Icon&size=10&auto=yes&text=TechFitU" alt="logo">
        {% include "store/_brandname.html" %}
        {% endblock %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for ('site.home') }}">
                    <i class="fa fa-home"></i>
                    Home
                    <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for ('users.user_alerts') }}">
                    <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                    My Alerts
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i class="fa fa-envelope-o">
                        <span class="badge badge-danger">11</span>
                    </i>
                    Messages


                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('site.contact') }}">
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                    Contact</a>
            </li>

            <!--<li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>-->
            <!--<li class="nav-item dropdown">-->
            <!--<a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>-->
            <!--<div class="dropdown-menu" aria-labelledby="dropdown01">-->
            <!--<a class="dropdown-item" href="#">Action</a>-->
            <!--<a class="dropdown-item" href="#">Another action</a>-->
            <!--<a class="dropdown-item" href="#">Something else here</a>-->
            <!--</div>-->
            <!--</li>-->
        </ul>
        {#<form class="form-inline my-2 my-lg-0">
            <div class="card-body row no-gutters align-items-center">

                <!--end of col-->
                <div class="col">
                    <input class="form-control form-control-lg form-control-borderless" type="search"
                           placeholder="Search alerts or keywords">
                </div>
                <!--end of col-->
                <div class="col-auto">

                    <button class="btn btn-lg btn-success" type="submit">
                        <i class="fa fa-search" aria-hidden="true"></i>
                        Search
                    </button>
                </div>
                <!--end of col-->
            </div>
        </form>#}

        <ul class="navbar-nav navbar-right">
        {% if not current_user.is_anonymous %}

            <li class="nav-item dropdown my-2 mr-auto">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    {{ current_user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ url_for ('users.show_profile') }}">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="{{ url_for ('users.logout') }}">
                        <i class="fa fa-sign-out" aria-hidden="true"></i>
                        Logout
                    </a>
                </div>
            </li>

        {% else %}

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for ('users.login_user') }}">
                    <i class="fa fa-sign-in" aria-hidden="true"></i>
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for ('users.register_user') }}">
                    <i class="fa fa-user-plus" aria-hidden="true"></i>
                    Sign Up
                </a>
            </li>

        {% endif %}
        </ul>


    </div>
</nav>
{% endblock %}

{% block content %}
<div class="container">

    {% with msgs = get_flashed_messages(category_filter=["success"]) %}
    {% if msgs %}
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-success" role="alert">
                <p>
                    {%- for msg in msgs %}
                    {{ msg }}
                    {% endfor -%}
                </p>

            </div>

        </div>

    </div>

    {% endif %}
    {% endwith %}

    {% with errors = get_flashed_messages(category_filter=["error"]) %}
    {% if errors %}
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <ul>
                    {%- for msg in errors %}
                    <li><strong>{{ msg }}</strong></li>
                    {% endfor -%}
                </ul>
            </div>

        </div>

    </div>

    {% endif %}
    {% endwith %}

    {% block main %}
    {% endblock %}
</div>

<!-- Site footer -->
{% block footer %}

<footer>
    <div class="container-fluid bg-dark py-3">
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <div class="row py-0">
                        <div class="col-sm-1 hidden-md-down">
                            <a class="bg-circle bg-info" href="#">
                                <i class="fa fa-2x fa-fw fa-address-card" aria-hidden="true "></i>
                            </a>
                        </div>
                        <div class="col-sm-11 text-white">
                            <div>
                                <h4>  Developers</h4>
                                <p>   <span class="header-font">Tech</span>Fit<span class="header-font">U</span>.com</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="d-inline-block">
                        <div class="bg-circle-outline d-inline-block" style="background-color:#3b5998">
                            <a href="https://www.facebook.com/"><i class="fa fa-2x fa-fw fa-facebook text-white"></i>
                            </a>
                        </div>
                        <div class="bg-circle-outline d-inline-block" style="background-color:#4099FF">
                            <a href="https://twitter.com/">
                                <i class="fa fa-2x fa-fw fa-twitter text-white"></i></a>
                        </div>

                        <div class="bg-circle-outline d-inline-block" style="background-color:#0077B5">
                            <a href="https://www.linkedin.com/company/">
                                <i class="fa fa-2x fa-fw fa-linkedin text-white"></i></a>
                        </div>
                        <div class="bg-circle-outline d-inline-block" style="background-color:#d34836">
                            <a href="https://www.google.com/">
                                <i class="fa fa-2x fa-fw fa-google text-white"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer><!--footer-->

<p class="text-center"> &copy; Company TechFitU. All right reserved. </p>
<!--/.footer-bottom-->


{% endblock %}

{% endblock %}

{% block scripts %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.9.4/holder.min.js" crossorigin="anonymous"></script>
{% endblock %}

pricealerts/templates/store/login.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_name %} Login {% endblock %}
{% block styles %}
{{super()}}

<link rel="stylesheet" href="{{ url_for ('static', filename='css/login-orig.css') }}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="col-md-12">
        <form class="form-signin needs-validation" method="post" novalidate>
            <img class="mb-4" src="../../assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
            <div class="text-center mb-4">
                <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
            </div>
            {{ form.hidden_tag() }}
            {{ wtf.form_errors(form, hiddens='only') }}

            {{ wtf.form_field(form.email) }}
            {{ wtf.form_field(form.password) }}
            {{ wtf.form_field(form.remember_me) }}
            <div class="row">
                <div class="col-md-6">
                    <button class="btn btn-success btn-lg  btn-block" type="submit">Sign in</button>
                </div>
                <div class="col-md-6">
                    <a href="{{ url_for ('users.register_user') }}" class="btn btn-lg btn-primary">Register</a>
                </div>
            </div>
            <p class="mt-5 mb-3 text-muted">&copy Your Prices Alerts - 2017-2018</p>
        </form>
    </div>
</div>

{% endblock %}


{% block scripts %}
{{super()}}
<script src="{{ url_for ('static', filename='js/sha512.min.js') }}" crossorigin="anonymous"></script>
<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();

    /*(function($){
        $(".form-signin").on('submit', function(e){

            e.preventDefault();
            $('#inputPassword').val(sha512($('#inputPassword').val()));

            //Detaching or unbinding the submit event with this handler.
            $(this).off( "submit" )

            //Submit the form
            $(this).submit();
        });
    })(jQuery)*/

</script>
{% endblock %}