pricealerts/views/users.py
import datetime
import os

import pytz
from flask import request, render_template, url_for, flash, Blueprint, current_app, send_from_directory
from flask_login import current_user, logout_user, login_required
from flask_login import login_user as session_login
from werkzeug.exceptions import NotFound
from werkzeug.utils import redirect, secure_filename

from pricealerts import settings
from pricealerts.forms import LoginForm, RegistrationForm
from pricealerts.models import UserErrors, ProfileModel
from pricealerts.models import UserModel
from pricealerts.utils.helpers import parse_phone, get_redirect_target

user_blueprint = Blueprint('users', __name__, url_prefix='/users', template_folder='templates')


@user_blueprint.route('/check_alerts/<string:user_id>')
@login_required
def check_user_alerts(user_id):
    pass


@user_blueprint.route('/myalerts', methods=['GET'])
@login_required
def user_alerts():
    # Look for the user's alerts and list them in the template
    alerts = current_user.get_alerts()
    for alert in alerts:
        alert.last_checked_delay = round((datetime.datetime.utcnow() - alert.last_checked).total_seconds() / 60, 2)
    return render_template('store/alerts.html', alerts=alerts)


#
# @user_blueprint.route('/login', methods=['GET', 'POST'])
# def login_user():
#
#     form = LoginForm()
#
#     validate = form.validate_on_submit() #  This is a shortcut for form.is_submitted()
#       (POST request) and form.validate().
#
#     if validate: # Checks if is POST and the form is valid
#         try:
#             UserModel.login_valid(request.form['email'], request.form['password'])
#
#         except UserError as loginEx:
#             session['username'] = None
#             flash(loginEx.message, category='error')
#             return render_template('store/login.html', form=form)
#
#         session['username'] = form.data['email']
#         return redirect(url_for('.user_alerts'))
#
#     return render_template('store/login.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if current_user.is_authenticated:
        return redirect(url_for('.user_alerts'))

    next_page = get_redirect_target()
    form = LoginForm()
    validate = form.validate_on_submit()  # This is a shortcut for form.is_submitted() and form.validate().

    if validate:  # Checks if is POST request and the form is valid
        try:
            user = UserModel.login_valid(form.data['email'], form.password.data)
            if user:
                session_login(user, remember=form.remember_me.data)
                user.last_login = datetime.datetime.utcnow()
                user.save_to_db()
                current_app.logger.info('%s logged in successfully', user.username)

                flash('User {0} logged in correctly'.format(user.name), 'success')
                # If the next page is not given or is url is outside the domain of the application
                # next_page will be the user alerts page
                return form.redirect(endpoint='.user_alerts')


        except UserErrors as loginEx:
            # Logout the user, just in case there is a session saved for this user previously
            logout_user()
            flash(loginEx.message, 'error')
            # return redirect(url_for('.login_user'))

    return render_template('user/login.html', title='Sign In', form=form)


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    form = RegistrationForm()  # data coming from client is got from request.form and request.files

    valid = form.validate_on_submit()  # Form is submitted using POST method and is valid data
    if valid:
        try:
            user = UserModel.register(form.data['email'], form.data['password'], form.data['name'], form.data['phone'])
            if user is not None:
                # After register, login in the user and redirecting to their alerts
                session_login(user)
                return redirect(url_for('.user_alerts'))
        except UserErrors as regError:
            flash(regError.message, 'error')
            # return redirect(url_for('.register_user'))

    print(form.data)
    print(form.email.errors)
    return render_template('user/register.html', title='Sign Up', form=form)


# @user_blueprint.route('/register',methods=['GET', 'POST'])
# def register_user():
#     form = RegistrationForm() # data coming from client is got from request.form and request.files
#
#     valid = form.validate_on_submit()
#     print(valid)
#     print(form.errors)
#     print(form.data)
#     if valid:
#         try:
#             if(UserModel.register(form.data['email'], form.data['password'], form.data['name'], form.data['phone'])):
#                 # After register, login in the user and redirecting to their alerts
#                 session['username'] = form.data['email']
#                 return redirect(url_for('.user_alerts'))
#         except UserError as regError:
#             flash(regError.message, category='error')
#             return redirect(url_for('.register_user'))
#
#     return render_template('store/register.html', title='Sign Up', form=form)

@user_blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('.login_user'))


# @user_blueprint.route('/logout')
# def logout():
#     session['username'] = None
#     return redirect(url_for('.login_user'))

TZ_DATA = [(v, v) for v in pytz.common_timezones]

@user_blueprint.route('/me', methods=['GET'])
@user_blueprint.route('<string:slug>/', methods=['GET'])
@login_required
def show_profile(slug=None):
    kwargs = { }

    if slug:
        profile = ProfileModel.find_one(slug=slug)
        if profile is None:
           raise NotFound('Profile not found')
        kwargs["show_user"] = profile.user
    else:
        kwargs["show_user"] = current_user

    if kwargs["show_user"] == current_user:
        kwargs["editable"] = True
    else:
        kwargs["editable"] = False


    return render_template('user/profile.html', **kwargs)

@user_blueprint.route('me/edit/', methods=['GET', 'POST'])
@login_required
def edit_profile():

    def allowed_file(filename):
        return '.' in filename and \
               filename.rsplit('.', 1)[1].lower() in settings.ALLOWED_EXTENSIONS

    error = None

    if request.method == 'POST':
        theme = request.form['theme']
        first_name = request.form.get('first_name', None)
        last_name = request.form.get('last_name', None)
        phone = request.form.get('phone', None)

        picture = request.files.get('picture', None)
        bio = request.form.get('bio', None)
        tz = request.form.get('tz', None)
        if 'picture' not in request.files:
            flash('No file part', category='error')
            return redirect(request.url)

        if phone != '' and phone is not None and not parse_phone(phone):
            error = 'Invalid phone. Suggested: 800-887-3244'
        elif not first_name:
            error = 'First name is required.'
        elif not last_name:
            error = 'Last name is required.'
        elif not tz:
            error = 'Timezone must be selected'

        elif picture is not None and not allowed_file(picture.filename):
            error = 'Not valid picture extension. Valid ones {}'.format(";".join(settings.ALLOWED_EXTENSIONS))

        if error is None:
            if current_user.profile is None:
                current_user.profile = ProfileModel()

            current_user.name = first_name + " " + last_name
            current_user.phone = phone
            current_user.theme = theme
            current_user.profile.bio = bio
            current_user.profile.timezone = tz

            filename = secure_filename(picture.filename)
            current_user.profile.picture = filename
            picture.save(os.path.join(settings.UPLOAD_FOLDER, filename))

            current_user.save_to_db()
            flash('User profile updated successfully', category='success')
            return redirect(request.url) # stay in the same page

        else:
            flash(error, category='error')

    first_name, last_name = current_user.name.split(" ")
    return render_template('user/edit_profile.html', user=current_user,
                           first_name=first_name, last_name=last_name, tz_data = TZ_DATA)

@user_blueprint.route('/me/changepassword', methods=['POST'])
@login_required
def changepassword():
    password = request.form.get('password', None)
    password2 = request.form.get('password2', None)

    from werkzeug.security import safe_str_cmp
    error=None
    if not password:
        error = 'Last name is required.'

    if not password2 or not safe_str_cmp(password, password2):
        error = "Passwords do not match"

    if error is None:
        current_user.set_password(password)
        flash('Password changed successfully', category='success')
    else:
        flash(error, category='error')

    return redirect(url_for('.edit_profile'))


@user_blueprint.route('/uploads/<filename>')
def uploaded_file(filename):
    '''
    Serving uploaded picture from the user.
    Function to return the file of that name

    :param filename:
    :return:
    '''
    with current_app.app_context() as context:
        return send_from_directory(current_app.config['UPLOAD_FOLDER'],
                               filename)

pricealerts/templates/user/login.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_name %} Login {% endblock %}
{% block styles %}
{{super()}}

<link rel="stylesheet" href="{{ url_for ('static', filename='css/login-orig.css') }}">
{% endblock %}



{% block content %}
<div class="container">
    {% with errors = get_flashed_messages(category_filter=["error"]) %}
    {% if errors %}
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <ul>
                    {%- for msg in errors %}
                    <li><strong>{{ msg }}</strong></li>
                    {% endfor -%}
                </ul>
            </div>

        </div>

    </div>

    {% endif %}
    {% endwith %}

    <div class="row">
        <div class="col-md-12">
        <form class="form-signin needs-validation" method="post" novalidate>
            <img class="mb-4" src="../../assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
            <div class="text-center mb-4">
                <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
            </div>
            {{ form.hidden_tag() }}
            {{ wtf.form_errors(form, hiddens='only') }}

            {{ wtf.form_field(form.email) }}
            {{ wtf.form_field(form.password) }}
            {{ wtf.form_field(form.remember_me) }}
            <div class="row">
                <div class="col-md-6">
                    <button class="btn btn-success btn-lg  btn-block" type="submit">Sign in</button>
                </div>
                <div class="col-md-6">
                    <a href="{{ url_for ('users.register_user') }}" class="btn btn-lg btn-primary">Register</a>
                </div>
            </div>
            <p class="mt-5 mb-3 text-muted">&copy Your Prices Alerts - 2017-2018</p>
        </form>
    </div>
    </div>
</div>

{% endblock %}


{% block scripts %}
{{super()}}
<script src="{{ url_for ('static', filename='js/sha512.min.js') }}" crossorigin="anonymous"></script>
<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();

    /*(function($){
        $(".form-signin").on('submit', function(e){

            e.preventDefault();
            $('#inputPassword').val(sha512($('#inputPassword').val()));

            //Detaching or unbinding the submit event with this handler.
            $(this).off( "submit" )

            //Submit the form
            $(this).submit();
        });
    })(jQuery)*/

</script>
{% endblock %}

pricealerts/templates/user/profile.html
{% extends "store/base.html" %}
{% block page_name %} User Profile {% endblock %}

{% block styles %}
{{super()}}
<style>

/* Profile page styling */
.profile-head {
    background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAYAAACp8Z5+AAAAJklEQVQIW2NkAIILFy78NzAwYATRjCABZEGwAEwFiA1WBlIOUwkA72gTdDIYVO4AAAAASUVORK5CYII=) repeat;
    padding: 70px 0px 30px 20px;
}
.profile-body {
    padding: 4px 0px;
}
</style>
{% endblock %}
{% block main %}

<div class="container profile-head">
  <div class="row">
    <div class="col-sm-10">
      <h1>{{ show_user.name }}</h1>
      {% if editable %}
      <a href="{{ url_for('users.edit_profile') }}" class="btn btn-info">Edit Profile</a>
      {% endif %}
    </div>
    <div class="col-sm-2">
        <img src="{% if show_user.profile.picture %} {{ url_for('users.uploaded_file', filename=show_user.profile.picture) }} {% else %} {{ url_for('static', filename='images/default_profile.png') }}  {% endif %}" class="rounded img-fluid img-thumbnail" alt="">
    </div>
  </div>
</div>

<div class="container profile-body">
  <div class="row">
    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item text-muted">{{ show_user.name }}'s profile</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Email:</strong></span> {{ show_user.username }}
	  {% if show_user.profile.email_verified %}
	    <span class="glyphicon glyphicon-ok-circle" aria-hidden="true" title="This email address has been verified"></span>
	    <span class="sr-only">Verified</span>
	  {% else %}
	    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true" title="This email address is not verified"></span>
	    <span class="sr-only">Not Verified</span>
	  {% endif %}
	</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Joined</strong></span> {{ show_user.created }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Last seen</strong></span> {{ show_user.last_login }}</li>

      </ul>
    </div>
    <div class="col-sm-8">
      <div class="panel panel-default">

       <div class="panel-body">

            <strong>API Key: <input type="text" class="form-control" disabled value="{{ show_user.api_key }}"/><br/><br/>
           <strong>Bio</strong>: {{ show_user.profile.bio }}
	</div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

pricealerts/templates/user/register.html
{% extends "bootstrap/base.html" %}
{% block page_name %} Sign Up {% endblock %}
{% block styles %}
{{super()}}

<link rel="stylesheet" href="{{ url_for ('static', filename='css/login-orig.css') }}">
{% endblock %}




{% block content %}

<div class="container">
    {% with errors = get_flashed_messages(category_filter=["error"]) %}
    {% if errors %}
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <ul>
                    {%- for msg in errors %}
                    <li><strong>{{ msg }}</strong></li>
                    {% endfor -%}
                </ul>
            </div>

        </div>

    </div>

    {% endif %}
    {% endwith %}
    <div class="row">
        <div class="col-md-12">
        <form class="form-signin needs-validation" method="post" action="" novalidate>
            <img class="mb-4" src="../../assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
            <h1 class="text-center h3 mb-3 font-weight-normal">!Lets check out!<br> Its Free to sign up</h1>
            {{ form.csrf_token }}
            {% if form.csrf_token.errors %}
            <div class="invalid-feedback is-invalid">You have submitted an invalid CSRF token</div>
            {% endif %}
            <div class="form-group">
                {{ form.name.label }}
                {{ form.name(class='form-control', placeholder="Name", required="required", autofocus="autofocus") }}
                <div class="valid-feedback">
                    Looks good!
                </div>
                <div class="invalid-feedback">
                    Please provide a valid name.
                    {% if form.name.errors %}
                    <ol>
                        {% for error in form.name.errors %}
                        <li><strong>{{ error }}</strong></li>
                        {% endfor %}
                    </ol>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                {{ form.email.label }}
                {{ form.email(maxlength=35, class='form-control', placeholder="Email address", required="required" ) }}
                <div class="invalid-feedback is-invalid">
                    {% if form.email.errors %}
                    <ol>
                        {% for error in form.email.errors %}
                        <li><strong>{{ error }}</strong></li>
                        {% endfor %}
                    </ol>
                    {% endif %}
                </div>
            </div>

            <div class="form-group">
                {{ form.phone.label }}
                {{ form.phone(class='form-control', placeholder="Phone") }}
                <div class="invalid-feedback is-invalid">
                    {% if form.phone.errors %}
                    <ol>
                        {% for error in form.phone.errors %}
                        <li><strong>{{ error }}</strong></li>
                        {% endfor %}
                    </ol>
                    {% endif %}
                </div>
            </div>

            <div class="form-group">
                {{ form.password.label }}
                {{ form.password(class='form-control', placeholder="Password", required="required") }}
                <div class="invalid-feedback is-invalid">
                    {% if form.password.errors %}
                    <ol>
                        {% for error in form.password.errors %}
                        <li><strong>{{ error }}</strong></li>
                        {% endfor %}
                    </ol>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                {{ form.confirm.label }}
                {{ form.confirm(class='form-control', placeholder="Password", required="required") }}
                <div class="invalid-feedback is-invalid">
                    {% if form.confirm.errors %}
                    <ol>
                        {% for error in form.confirm.errors %}
                        <li><strong>{{ error }}</strong></li>
                        {% endfor %}
                    </ol>
                    {% endif %}
                </div>
            </div>

            <div class="checkbox mb-3">
                <label>
                    {{ form.accept_rules }} {{ form.accept_rules.label }}
                    <!--<input type="checkbox" value="remember-me"> Remember me-->
                </label>
                <div class="invalid-feedback is-invalid">
                    {% if form.accept_rules.errors %}
                    <ol>
                        {% for error in form.accept_rules.errors %}
                        <li><strong>{{ error }}</strong></li>
                        {% endfor %}
                    </ol>
                    {% endif %}
                </div>
            </div>

            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>

        </form>
    </div>
    </div>
</div>


{% endblock %}

{% block scripts %}
{{super()}}
<script src="{{ url_for ('static', filename='js/sha512.min.js') }}" crossorigin="anonymous"></script>
<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();

    /*(function($){
        $(".form-signin").on('submit', function(e){

            e.preventDefault();
            $('#inputPassword').val(sha512($('#inputPassword').val()));
            //Detaching or unbinding the submit event with this handler.
            $(this).off( "submit" )

            $(this).submit();
        });
    })(jQuery)*/

</script>
{% endblock %}